vim.o.expandtab = true
vim.o.shiftwidth = 8
vim.o.tabstop = 8
vim.o.softtabstop = 8
vim.o.number = true
vim.o.relativenumber = true
vim.o.clipboard = "unnamedplus"
vim.o.wrap = false
vim.o.smartindent = true
vim.o.inccommand = "split"
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.swapfile = false
vim.o.backup = false
vim.o.undodir = vim.fn.stdpath("data") .. "/undodir"
vim.o.undofile = true
vim.o.scrolloff = 8
vim.o.colorcolumn = "110"
vim.o.guifont = "Iosevka NF"
